spring:
  application:
    name: usercontact
  datasource:
    dricvarClassName : com.mysql.jdbc.Driver
    url : "jdbc:mysql://localhost:3306/contactdetail?autoreconnect=true"
    password: "root"
    username: "root"
    
    dbcp2:
      testOnBorrow : true
      test-while-idle: true
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      max-active : 15
      max-idle: 10
      max-wait-millis: 1000 
  